### ISSUE TITLE
Moolticute not quitting properly on macOS Monterey

### ISSUE THREAD

**Issue by Lhudwolf** [mooltipass/moolticute#1090]
### Expected behavior

When i quit the program (CMD + Q) the process is killed. I can reopen Moolticute on macOS without using the terminal to manually kill the process.

### Actual behavior

I quit the program and Moolticute is not completly closed. I cannot reopen the program without firstly going into the terminal, pgrep moolticute and killing the provided PID manually.

### Step by step guide to reproduce the problem

1. Open Moolticute on macOS
2. Quit Moolticute on macOS
3. Try to reopen Moolticute on macOS

### Moolticute Version

v1.00.0

### Operating System

MacOS Monterey 12.6.1

**Comment by Lhudwolf** [comment]
I just read the changelog for v1.00.0 - just a quick note.

CMD + Q should minimize Moolticute according to the changelog. CMD+Q is the global command to quit apps on macOS. CMD+M is the usual command to minimize apps on macOS.

**Comment by ananthb** [comment]
I also have some new found weirdness on macOS. If I close the moolticute window I'm unable to reopen it without executing `pkill moolticute` first. Also when moolticute doesn't open, plugging in the mooltipass usually throws up a 'Too Many Connections'  error or something similar on the device's screen.

**Comment by limpkin** [comment]
The "too many connections" error means that a bluetooth device is trying to connect to the Mini BLE with outdated/invalid pairing data

**Comment by ananthb** [comment]
Yep that makes sense. I had reset my device but the mac was still trying to connect.

Another slight weirdness after installing the new moolticute is that I now get three dock icons for moolticute whenever I run it.
<img width="325" alt="Screenshot 2022-12-02 at 09 39 24" src="https://user-images.githubusercontent.com/3133350/205212959-68847c73-b39f-4203-9f18-ad48c40601b3.png">

**Comment by limpkin** [comment]
I'm wondering if a new icon doesn't popup every time an update is installed.... @deXol

**Comment by ananthb** [comment]
I tried removing them after the update but these three keep coming back.

**Comment by limpkin** [comment]
@deXol do you experience this as well?

**Comment by ananthb** [comment]
The extra icons are now gone from my dock. Not sure what has changed but it disappeared after a reboot. I reboot very infrequently so maybe something lingered from the previous moolticute update.

Also, I can't re-open the closed moolticute window from the dock icon. But, I can reopen it from the notification tray icon. This is perfectly functional for me.

**Comment by Lhudwolf** [comment]
@limpkin for me this issue still persist. To actually quit moolticute i have to pgrep moolticute --> kill the PID

This should therefore also be connected to this issue #1146

**Comment by jms1voalte** [comment]
This is happening for me as well. (Moolticute v1.03.0 on macOS 14.4.1 Intel.)

FWIW, I didn't realize there *was* a background widget involved, I use [Bartender](https://www.macbartender.com/) to hide many of the menu bar items. I just right-clicked the menu item and chose "Quit", and while it did take about 6-7 seconds to shut down, it *did* fully shut down, and then I was able to run the app again. So that's something.

Maybe Moolticute should have a setting to shut down the "background part" when the foreground UI is closed? Especially for people like me who don't use Moolticute for anything other than managing credentials on my Mooltipass devices (i.e. I don't use them for FIDO, SSH, or anything - that's what Yubikeys are for).

Also ... regardless of this as-yet-nonexistent setting, if I close the foreground program and then start it again, shouldn't it try to connect to a running background process before trying to start a new one? (Also, shouldn't the foreground process actually *terminate* rather than stay running with no UI?)
