### ISSUE TITLE
Search and Replace passwords in moolticute

### ISSUE THREAD

**Issue by Mixer9** [mooltipass/moolticute#1205]
### Missing feature
The ability to search and replace based on password or portion of password in moolticute
### Justification
At my place of work we have SSO and as such have many domains / sub domains that all use the same SSO credentials, this ends up being multiple entries in the mooltipass. Ie. stuff.bob.com, dev.bob.com, hold.dev.bob.com .  When I change my password in the SSO system, I then have to change the password in multiple entries. If I could search and replace by password then I could more easily manage the password changes.

### Workarounds
No workarounds, you must change each entry manually.

**Comment by Ancyker** [comment]
I feel like domain aliases (i.e. treat `example.org` like `example.com`) would be better since it would help eliminate the redundant data from existing to begin with. It might also save space on the device. Personally, I'd be fine with aliases being entirely on the app side of things and not stored directly on the device.

**Comment by limpkin** [comment]
domain aliases are indeed the solution to such a problem.
