### ISSUE TITLE
Why is the updater so slow at downloading

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#135]
I'm using Windows 10. The downloader took multiple minutes to download the 0.9.10 beta update, but it took me just a few seconds to download it from the GitHub Releases page. Why so slow?

**Comment by limpkin** [comment]
Hello Noah,

This is because at the moment the file is downloaded from another place.
We will therefore change it to github!

Mathieu

On Oct 21, 2017 3:34 AM, "Noah Andrews" <notifications@github.com> wrote:

I'm using Windows 10. The downloader took *multiple minutes* to download
the 0.9.10 beta update, but it took me just a few seconds to download it
from the GitHub Releases page. Why so slow?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mooltipass/moolticute/issues/135>, or mute the thread

**Comment by limpkin** [comment]
fixed with recent PR
