### ISSUE TITLE
knock-knock doesn't work in moolticute

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#205]
I cannot confirm downloading or exporting a file by knocking on my desk. I have to press on the wheel instead.
However, I can knock to confirm logins in the browser (chrome + mp plugin).

I can reproduce this by switching between moolticute and the browser without removing the card or disconnecting the usb. Login works - multicute confirm doesn't. 
I can also reproduce this on my second mooltipass device.

0.11.7-beta (wish I could cut'n paste the version)

**Comment by limpkin** [comment]
Hello Alan,

I'm afraid this is by design on the mini, and can be traced back to here: https://github.com/limpkin/mooltipass/blob/master/source_code/src/GUI/mini_gui_screen_functions.c#L655.

In short, there is no knock to approve to download files.. but we'll implement it in a next firmware iteration.

**Comment by alanrick** [comment]
funny - I thought it was just me imagining things.
