### ISSUE TITLE
Discussion ticket about interaction between moolticuted and remote emulator.

### ISSUE THREAD

**Issue by sbobykin** [mooltipass/moolticute#223]
## Common notes.

We (https://github.com/Grandison-RG) offer to create a separate low level Mooltipass emulator called `mpemu` as a microservice implemented in Haskell programming language. For transport we propose to use websockets protocol.

From our point of view this approach has two notable advantages.

**Microservice** allows every program to commune  with low level Mooltipass emulator. For example: that could be a mobile application of some kind which runs on a real device or in (mobile OS) simulator.

**Haskell** is only one production ready language for this kind of tasks that allows to create programs without side effects and with good constructive abilities. 

To reach the goal we offer to modify the `moolticuted` source to allow communication between proposed microservice (low level emulator) and `moolticuted`.

For this point we’ve added `-m` option that opens websocket based communication with remote emulator. Actual realization consists of modifications in the files:  `Appdaemon.h`,  `Appdaemon.cpp` `MPManager.h`, `MPManager.cpp`, and additions of two new files: `MPDevice_emul_remote.h`, `MPDevice_emul_remote.cpp`.

Let us explain the proposed modifications in detail.

## Modifications of the `moolticute` source.

**Modifications in `Appdaemon.h` and `Appdaemon.cpp`**
We added `-m` option in these files. As a result we have two emulation modes: local (`-e`) and remote (`-m`) we have set the higher priority to local mode (`-e` option). That means that if you run `./moolticuted -e -m` then it's equal to  `./moolticuted -e`.  

 We have substituted one boolean function to make things simpler:

- `bool AppDaemon::isEmulationMode()  //true if only` `'``-e``'` `is set`

by the list of functions

- `bool AppDaemon::isEmulationModeLocal() //true if '-e' is set`
- `bool AppDaemon::isEmulationModeRemote() //true if '-m' (without '-e') is set`
- `bool AppDaemon::isEmulationMode() //true if only (xor) one of '-e' or '-m' is set`

**Modifications in `MPManager.h` and `MPManager.cpp`**
We have included `MPDevice_emul_remote.h` in this set of files. We had to change only once old `bool AppDaemon::isEmulationMode()` into the new `bool AppDaemon::isEmulationModeLocal()` because of using new variant of `bool AppDaemon::isEmulationMode()` and add `else if (AppDaemon::isEmulationModeRemote())` , where we activate  `MPDevice` associated with the remote emulator.

**Addition of `MPDevice_emul_remote.h` and `MPDevice_emul_remote.cpp`**
In these files we’re developing the websocket communication with remote emulator.

**Watching of “work in progress”.**
To review the current “work in progress” you can simply do the following:

    git clone https://github.com/Grandison-RG/moolticute.git
    git diff master..emuws

## About pull request into the `moolticute` upstream.

We believe in the approach proposed by us, because separate low level emulator daemon allows us to make Mooltipass echo system richer and attractable. For example, people who decide to create mobile application could have a ready to go the low level Mooltipass emulator.

At the same time we understand that the upstream team need to make a deep review and discuss a lot of things with us before merging. And there is no any problems for us. We can continue to create `mpemu` and move carefully to a pull request of our proposed modifications into the `moolticute` upstream.

Upstream team we only ask you. Please give us feedback. Thanks.

**Comment by limpkin** [comment]
Hello,
thanks for the explanation... please write a message here when you think the **exact** required changes (code included) are implemented in your fork.
We particularly want to see the actual changes in our code.

**Comment by sbobykin** [comment]
@limpkin thanks for your reply.

Below is a diff that reflects modifications in the Moolticute structure.

As you can see we can split the task into two parts: modifications of Moolticute and development of the websockets stuff. Currently we need some feedback about the first one.

Discussion is very important cause it's the only way to go forward together.

```
diff --git a/daemon.pro b/daemon.pro
index 4d20653..6c94a3e 100644
--- a/daemon.pro
+++ b/daemon.pro
@@ -63,6 +63,7 @@ SOURCES += src/main_daemon.cpp \
     src/MPNode.cpp \
     src/WSServerCon.cpp \
     src/MPDevice_emul.cpp \
+    src/MPDevice_emul_remote.cpp \
     src/http-parser/http_parser.c \
     src/HttpClient.cpp \
     src/HttpServer.cpp \
@@ -83,6 +84,7 @@ HEADERS  += \
     src/version.h \
     src/WSServerCon.h \
     src/MPDevice_emul.h \
+    src/MPDevice_emul_remote.h \
     src/http-parser/http_parser.h \
     src/HttpClient.h \
     src/HttpServer.h \
diff --git a/src/AppDaemon.cpp b/src/AppDaemon.cpp
index 8e7adea..261007d 100644
--- a/src/AppDaemon.cpp
+++ b/src/AppDaemon.cpp
@@ -25,7 +25,8 @@
 #include "MacUtils.h"
 #endif
 
-bool AppDaemon::emulationMode = false;
+bool AppDaemon::emulationModeLocal = false;
+bool AppDaemon::emulationModeRemote = false;
 
 AppDaemon::AppDaemon(int &argc, char **argv):
     QAPP(argc, argv),
@@ -90,9 +91,13 @@ bool AppDaemon::initialize()
     parser.addHelpOption();
     parser.addVersionOption();
 
-    QCommandLineOption emulMode(QStringList() << "e" << "emulation",
+    QCommandLineOption emulModeLocal(QStringList() << "e" << "emulation",
                                      QCoreApplication::translate("main", "Activate emulation mode, all Websocket API function return emulated string, usefull if you want to try the API."));
-    parser.addOption(emulMode);
+    parser.addOption(emulModeLocal);
+
+    QCommandLineOption emulModeRemote(QStringList() << "m" << "emulation-remote",
+                                      QCoreApplication::translate("main", "Open connection with remote emulator."));
+    parser.addOption(emulModeRemote);
 
     // An option with a value
     QCommandLineOption debugHttpServer(QStringList() << "s" << "debug-http-server",
@@ -102,7 +107,8 @@ bool AppDaemon::initialize()
 
     parser.process(qApp->arguments());
 
-    emulationMode = parser.isSet(emulMode);
+    emulationModeLocal = parser.isSet(emulModeLocal);
+    emulationModeRemote = !emulationModeLocal && parser.isSet(emulModeRemote); //'-e' has higher priority
 
     if (parser.isSet(debugHttpServer))
     {
@@ -136,7 +142,17 @@ AppDaemon::~AppDaemon()
     delete httpServer;
 }
 
+bool AppDaemon::isEmulationModeLocal()
+{
+    return emulationModeLocal;
+}
+
+bool AppDaemon::isEmulationModeRemote()
+{
+    return emulationModeRemote;
+}
+
 bool AppDaemon::isEmulationMode()
 {
-    return emulationMode;
+    return emulationModeLocal ^ emulationModeRemote;
 }
diff --git a/src/AppDaemon.h b/src/AppDaemon.h
index 67f6f7a..bb568d3 100644
--- a/src/AppDaemon.h
+++ b/src/AppDaemon.h
@@ -45,6 +45,8 @@ public:
 
     bool initialize();
 
+    static bool isEmulationModeLocal();
+    static bool isEmulationModeRemote();
     static bool isEmulationMode();
 
 private:
@@ -57,7 +59,9 @@ private:
     //this is to send out logs to gui app
     QLocalServer *localLogServer = nullptr;
 
-    static bool emulationMode;
+    //static bool emulationMode;
+    static bool emulationModeLocal;
+    static bool emulationModeRemote;
 };
 
 #endif // APPDAEMON_H
diff --git a/src/MPManager.cpp b/src/MPManager.cpp
index 82d149a..95696f3 100644
--- a/src/MPManager.cpp
+++ b/src/MPManager.cpp
@@ -155,7 +155,7 @@ void MPManager::checkUsbDevices()
     }
 
 
-    if (AppDaemon::isEmulationMode())
+    if (AppDaemon::isEmulationModeLocal())
     {
         MPDevice *device;
         device = new MPDevice_emul(this);
@@ -163,6 +163,14 @@ void MPManager::checkUsbDevices()
         devices["EMULDEVICE_ID"] = device;
         emit mpConnected(device);
     }
+    else if (AppDaemon::isEmulationModeRemote())
+    {
+        MPDevice *device;
+        device = new MPDevice_emul_remote(this);
+        detectedDevs.append("EMULDEVICEREMOTE_ID");
+        devices["EMULDEVICEREMOTE_ID"] = device;
+        emit mpConnected(device);
+    }
     else
     {
         foreach (const MPPlatformDef &def, devlist)
diff --git a/src/MPManager.h b/src/MPManager.h
index f24e553..085444e 100644
--- a/src/MPManager.h
+++ b/src/MPManager.h
@@ -29,6 +29,7 @@
 #include "MPDevice_linux.h"
 #endif
 #include "MPDevice_emul.h"
+#include "MPDevice_emul_remote.h"
 
 class MPManager: public QObject
 {

```

**Comment by qb-anssi** [comment]
Hi,

Follow are my comments that does not looks into on the CPP code itself.

The first things I notice is that you gave generic explanation on why the creation
of external emulator and then mpemu is needed, but not really why you
are doing it.

> we have set the higher priority to local mode

I disagree with this statement, its seems that now and in the future it makes
no sense to have both local an remote emulator so having one argument taking over
is understandable to me. If local and remote are exclusive and if the moolticuted
is ran with both the program should abort and print an usage message.
Eventually, you could transform argument parsing to have something like
`--emulator-mode {local|remote}`

One things that I would appreciate is to remove as much as possible of emulation
code. Its probably very useful in some case, but in term of "production" I really
don't like this concept. I will appreciate that you provide a way to remove
emulation code at build-time. For me it should both target local and remote mode.
Among you work I will deeply appreciate one PR for that.

Looking at the provided code, I saw some dead code that should be removed:
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/AppDaemon.h#L62
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.cpp#L16
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.cpp#L39

Looking at the provided code, I saw some hardcoded value, that should be translated
by argument parsing AND configuration file, especially if you would like to
create a richer environment.
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.cpp#L11

Looking at the provided code, I without knowing much about what those function
are but calling to `open()`, `connect()` or `read()` implies that the status code
MUST be checked.
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.cpp#L8
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.cpp#L11
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.h#L13

Looking at the provided code, I saw some trailing white space:
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPDevice_emul_remote.h#L10

Looking at the provided code, I saw lot of common code, I will see something
like template/class/struct that both local and remote inherit from
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPManager.cpp#L158
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPManager.cpp#L166

Looking at the provided code, you should probably assert that creating the emulator
device does not fail.
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPManager.cpp#L161
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/MPManager.cpp#L169

Looking at the existing code there is already some "lib" that handle
web-socket, I would deeply like that you start from here, eventually make name
more clear and use them for your web-socket based communication instead of
rolling-your-own.
  * https://github.com/Grandison-RG/moolticute/blob/891e14b8ff5e9aeafd092aef6e83c05209fd8a8e/src/WSClient.cpp#L24

Looking at the filename I spot some consistency problems with how you name your
files. Some are not from you, but among your work I will deeply appreciate one PR
to standardize file naming in the project. It seems that camel case is preferred
over name that start with camel case then switch to underscore without capitalization.
An example will be `src/MPDevice_emul_remote.h̀`, this naming is non-sense to me.

**Comment by sbobykin** [comment]
@qb-anssi  , thanks for your deep and great review.  We’d like to continue this healthy technical discussion. Your notes are very well. They really allow to move forward. Thanks a lot again.

There are our answers on your notes below. And we hope to continue discussion.


## “but not really why you are doing it”
- At first, all we need emulation in the Mooltipass project.
- Our team wants to do it in Haskell
- That’s not good to embed the Haskell code into the Moolticuted C++ code
- So we need a separate solution (and microservice is a good choice)
- BTW microservice approach has some advantages which we have described before.


## Disagreement about higher priority of local mode.

That’s very good note. And in the case of using `-e` and `-m` options together now we show error message about it (according to your wise proposal). That was an attempt to activate both modes;  `moolticuted` presently supports the only one connected device, because of that we allow the only one emulation mode.

See the patch to reflect our modifications:

    diff --git a/src/AppDaemon.cpp b/src/AppDaemon.cpp
    index 261007d..ab9d7b0 100644
    --- a/src/AppDaemon.cpp
    +++ b/src/AppDaemon.cpp
    @@ -16,6 +16,9 @@
      **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
      **
      ******************************************************************************/
    +#include <stdio.h>
    +#include <stdlib.h>
    +
     #include "AppDaemon.h"
     #include "HttpServer.h"
     #include "Common.h"
    @@ -108,7 +111,13 @@ bool AppDaemon::initialize()
         parser.process(qApp->arguments());
     
         emulationModeLocal = parser.isSet(emulModeLocal);
    -    emulationModeRemote = !emulationModeLocal && parser.isSet(emulModeRemote); //'-e' has higher priority
    +    emulationModeRemote = parser.isSet(emulModeRemote);
    +    if(emulationModeLocal && emulationModeRemote) {
    +        QString errmsg = QCoreApplication::translate("main", "Only one emulation device is allowed. Use either 'e' or 'm'.");
    +        fputs(qPrintable(errmsg), stderr);
    +        fputs("\n", stderr);
    +        return false;
    +    }
     
         if (parser.isSet(debugHttpServer))
         {


## "I will see something like template/class/struct that both local and remote inherit from"

That would be awesome to have some elegant code of this kind. And we thought about that. But the current implementation is stable. If we begin to restructure `moolticuted`,  then we can bring some new bugs.


## Code in the `MPDevice_remode_emul.cpp` and `MPDevice_remode_emul.h` files.

The code in these files has a “work in progress” status presently. But that’s very important to have discussion about restructuring `mooltcuted` in the parts out of these files cause we'd like to stabilize them (the parts) as soon as possible.

**Comment by qb-anssi** [comment]
Hey @sbobykin, glad you would like to move forward!

> Our team wants to do it in Haskell

My question may not have been clear enough, what I was looking is why your team wants to have an Mooltipass emulator? I'm specially looking at the story behind your project. Eventually, you could understand the question like: why are you implementing an emulator instead of feature `<xyz>`.
That's a non technical question. Eventually it may be useful to better integrate you and any further commit one may perform against moolticute repository.

In order to bounce on you answer:
  > Haskell

Why not if you like it;

  > Separate than moolticute

Seems obvious that this is a sane choice;

# CLI arguments parsing
[About the error message](https://github.com/Grandison-RG/moolticute/blob/3d80c3e8a415f522e9765ebce5195b69d7d9bb80/src/AppDaemon.cpp#L116), we are going into the good direction however, I would really see something like a real call to a real usage method.
Like in another [daemon](https://github.com/openssh/openssh-portable/blob/3fd2d2291a695c96a54269deae079bacce6e3fb9/sshd.c#L898)

Also its seems that this is the only place in the code base that one call to [fputs](https://github.com/Grandison-RG/moolticute/blob/3d80c3e8a415f522e9765ebce5195b69d7d9bb80/src/AppDaemon.cpp#L117), seems wrong to me?

Going futher with the [emulation mode getters](https://github.com/Grandison-RG/moolticute/blob/3d80c3e8a415f522e9765ebce5195b69d7d9bb80/src/AppDaemon.cpp#L166), there is two points here I would like to emphathis:
  * You are not using you own functions 'isEmulationModeLocal' 'isEmulationModeRemote'
  * Known that we defined that only one emulation mode is supported the XOR seems hard to understand

# Template issue

> That would be awesome to have some elegant code of this kind. And we thought about that. But the current implementation is stable. If we begin to restructure moolticuted, then we can bring some new bugs.

Yes and no, but mostly no: The best way to not adding code, is to not adding anything to the code base. You will and should be prepared to bug. This include at least tests, return status check and reducing the amount of duplicate code, so if any bug is found its only has to be fix in one single place instead of just live patching on branch and not the others.


# Code in the MPDevice_remode_emul.cpp and MPDevice_remode_emul.h files.

> The code in these files has a “work in progress

I was more commenting on the filename.

Sure, it would be great to continue our discussion!
~

**Comment by limpkin** [comment]
Hello there,

It has been a month since mpemu repository has been udpated... is your project still ongoing?

**Comment by Elvecent** [comment]
Hi everyone! We did kind of take an unintentional break. Nevertheless, we are not abandoning our work. Hopefully there will be some update in less than a week.

**Comment by limpkin** [comment]
seems like this is never going to happen.....
