### ISSUE TITLE
Intrusive update notification / popup

### ISSUE THREAD

**Issue by haadr** [mooltipass/moolticute#263]
Hi and thanks for a great app!

Today I was working, having the moolticute app running in the background, when, while talking to others and showing them things on my screen, moolticute decided to pop up a notification telling me about a new update. While I would prefer automatic checks for updates not to be the default behaviour, I think it should be considered a bug for an application running in the tray to produce a pop up at some random time.

Conceivable, moolticute is something you always have running in the background/tray. So if I am doing a presentation or in some other way presenting things, this might simply pop up. I would ask that any notifications only pop up when the window is active and visible, at least. 

What do you think?

Thanks again!

PS: I found https://github.com/mooltipass/moolticute/issues/42 but I think this is a separate issue, as I'm mostly concerned with the popup being intrusive.

**Comment by limpkin** [comment]
@raoulh : does Qt provide tray notifications for all 3 OSes?

**Comment by haadr** [comment]
Just to be clear: 

I'm talking about a what looks like a  pop-up window which appears above all current windows even though moolticute is currently "in" the tray. The pop-up doesn't look like a tray notification. 

I'm on plasma/KDErunning Debian stretch, if that helps.

**Comment by raoulh** [comment]
@limpkin what do you mean by "tray notifications"?

@haadr is right we need a better way to present the user that an update is available. We need to "force" a bit users to do the update (if it's a security fix it must be updated) but not too hard to not bother users too much.

One thing is if we don't show a popup like the actual one, but instead display something only when you open the MC gui, is that users would only do updates when they open the gui. This can be not so good if users don't open the gui that much (like me, I only open the gui once or two a week). For some critical security updates, that's not good at all.

Some ideas here:
 - On debian/ubuntu: provide our own repository or ppa, this would allow users to update MC using the standard system update tools (which is better integrated than something we cool develop ourselves)
 - On windows: automatic update installation in background
 - on macos: maybe check if we could use tha appstore for deploying MC? This could be difficult because of the sanboxing of appstore's apps.

**Comment by tmontney** [comment]
Although not followed up by OP, this is a good idea. Perhaps the dialog that appears has a checkbox to silence/move to tray (with ability to change at later time in the app itself). The user should have full control over notifications, setting the default to notify fully.

@raoulh If a release contains a security/critical update, then notifications should reflect that in the app (if they don't already). If it looks like "just another update", users are going to ignore (because everything wants to update and everything "is important"). The app should know the difference between routine updates and critical (e.g. in app, users can hide normal update notifications but show critical ones).

**Comment by limpkin** [comment]
suggestion implemented!
