### ISSUE TITLE
json connection encryption

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#417]
In order to improve our ecosystem, it would be good to encrypt the connection between the daemon and any other client (plugin or mc-cli).
I'm imagining a standard diffie-hellman exchange followed by AES-CBC. If I'm not mistaken, authentication of the daemon isn't required as only one program can listen to a given port number.

**Comment by raoulh** [comment]
The daemon exposes a websocket server. As such the best way to add encryption is to use https intead of the default http (websocket uses http underneath). All clients can directly handle encryption because supporting https is available everywhere and it's the recommended way to encrypt data over http.

We could also imagine to save the ssl certificate on the device eventually.

The only real problem will be our browsers extensions. They will need to connect to the https://localhost, but the certificate validation will fail as it would be self signed and all browser will fail to do so with maybe security warnings.
A solution for that would require to add the CA of the certificate to the trusted root CA in the browser... Not really convenient for end users.

**Comment by deXol** [comment]
Found Crypto++ for C++ (https://cryptopp.com) this contains a lot cryptographic methods including the Diffie-Hellman which you mentioned. But it is a big library and as I checked [not so straight forward](https://stackoverflow.com/questions/38893334/using-crypto-static-library-in-a-qt-project) to use from Qt project, especially for every platform.
Also checked [Chilkat](https://www.example-code.com/cpp/dh_key_exchange.asp), but it is also a huge dependency.
Maybe it would be easier to add the implementation for it. There are a few examples for that:

- https://www.codeproject.com/Articles/70330/Implementation-of-Diffie-Hellman-Algorithm-of-Key
- https://www.geeksforgeeks.org/implementation-diffie-hellman-algorithm/

For browser extension (JS) I also found some implementation e.g.: 
https://github.com/crypto-browserify/diffie-hellman
I am not too familiar with extension code, but I think something like this could be integrated to it.

**Comment by raoulh** [comment]
Actually MC is already shipped with openssl, so if we go that route (DH on our own) I would prefer to use openssl directly instead of yet another crypto lib.

**Comment by limpkin** [comment]
closing given #459
