### ISSUE TITLE
Keep looking for USB devices when connected through Bluetooth

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#702]
not 100% sure this isn't implemented yet...

**Comment by deXol** [comment]
This one was implemented before but in https://github.com/mooltipass/moolticute/pull/565 we had a modification, where if we have a connected device stop looking for other devices.
What is the expected behavior in this case, if BLE is connected with BT, but we connect it with USB too I guess we should use the USB connection. 
But what if we connect a different BLE device with USB or even a mini device? Should we continue using with BT the first BLE device or always prefer USB connection?

**Comment by limpkin** [comment]
always prefer USB :)
