### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by NicoHood** [mooltipass/moolticute#745]
I've seen some very old Reddit post about this, but is there a way to export the database to a plain text file etc?

**Comment by limpkin** [comment]
Given the encryption key is stored inside the smart card, there is a way to
extract your credentials from a backup file using the following script and
a smart card reader :
https://github.com/mooltipass/minible/tree/master/scripts/smc_decode

Please note that if you are planning to use this script, you are
effectively voiding the mooltipass security model, which is why we strongly
suggest you not to.

If you feel we correctly addressed the issue, please feel free to close it.

**Comment by NicoHood** [comment]
Could you maybe give me some more details? Which parameters can be used and how the final file format will look like? I have worries, that the script fails while it is half way through. Is it possible that the script could damage the mooltipass itself?

**Comment by limpkin** [comment]
What do you mean by parameters? It simply asks for the path to your backup
file and connects to the smart card reader. All credentials will be output
to the current window.
No danger for the mooltipass.

**Comment by Frankstar** [comment]
is this also possible with the mooltipass itself as a smarcard reader?
Im planing to export the whole database in a readable format.

**Comment by limpkin** [comment]
unfortunately not at the moment

**Comment by Frankstar** [comment]
so 2 years later - sadly no new mooltipass device and no old one either. how can we export or data? still with [this](https://github.com/mooltipass/minible/tree/master/scripts/smc_decode)? im planning to migrate to bitwarden.
