### ISSUE TITLE
Cant set TOTP secret longer than 49 characters

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/moolticute#791]
Cant set TOTP secret longer than 48 characters.
Example:
Amazon.com uses longer TOTP secret.

Also after setting a secret can't view it after.

**Comment by limpkin** [comment]
pinging @0x0ptr : is this also a hw limitation?

**Comment by 0x0ptr** [comment]
@WebmasterTD Thanks for reporting!

@limpkin The Amazon TOTP appears to be 52 characters encoded (which turns out becomes (52*5/8) 32.5 bytes decoded (!)). Strange that they don't use 56 characters which would give an even decoded binary key but I guess that doesn't really matter.

We currently limit the decoded key to 32 bytes both in the messages and in the database so this won't fit. If we increase the number of supported bytes we would then go to 48 bytes then probably (AES block size x 3)? That would give support for up to 72 characters (45 bytes decoded) of TOTP.

**Comment by limpkin** [comment]
@0x0ptr damn, i'm still not getting github notifications :/. 48 bytes sounds like a good plan, do you have some time these days? :)

**Comment by limpkin** [comment]
or if it's just that #define to change then i can do it as well :)

**Comment by 0x0ptr** [comment]
@limpkin yes, if i did my job it should be just that! Feel free to do it yourself :-)

**Comment by limpkin** [comment]
implemented on the minible repo (secret size increased to 64 bytes). moolticute update to follow

**Comment by limpkin** [comment]
done! available in next release :)
